name: SkillX
version: '${version}'
main: skillx.SkillX
api-version: 1.19
libraries:
    - org.jetbrains.kotlin:kotlin-stdlib:1.7.20
    - org.jetbrains.kotlin:kotlin-reflect:1.7.20

commands:
    select:
        description: open select inventory
        usage: /select
        permission: skillx.debug.select