name: SkillX
version: '${version}'
description: SkillX plugin for paper
website: https://github.com/techest/SkillX
authors:
  - PleahMaCaka
main: skillx.SkillX
api-version: '1.20'
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.0
  - org.jetbrains.kotlin:kotlin-reflect:1.9.0
